### ISSUE TITLE
Be aware of the bug on version 1.30.0 of Sentry-SDK

### ISSUE THREAD

**Issue by xpepper** [emmett-framework/sentry#1]
See https://github.com/getsentry/sentry-python/issues/2340 and https://github.com/getsentry/sentry-python/pull/2347.

Setting the min version in poetry from v.1.31.0 should fix this.

**Comment by gi0baro** [comment]
@xpepper thank you, this should be fixed with https://github.com/emmett-framework/sentry/commit/fd96df80d9c8dc23d931c906943052982090858c and in 0.6.1
